# Generated by Django 3.2.4 on 2023-04-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.PositiveIntegerField()),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('valor_neto', models.PositiveIntegerField()),
                ('iva', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nro_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('giro', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('direcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nombre', models.CharField(max_length=50)),
                ('cant', models.PositiveIntegerField()),
                ('precio_unit', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('factura_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
    ]
