# Generated by Django 3.2.4 on 2023-05-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='factura_detalle',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direcc',
        ),
        migrations.RemoveField(
            model_name='registro_solicitud',
            name='nro_factura',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Registro_Solicitud',
        ),
    ]
