# Generated by Django 3.2.4 on 2023-05-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_proveedor_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.PositiveIntegerField(choices=[(1, 'Mobiliario'), (2, 'Aseo'), (3, 'Quimica'), (4, 'Accesorio de Computadora')]),
        ),
    ]
