# Generated by Django 3.2.4 on 2023-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_categoria_tipo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
